notifications:
  email: false

language: c

before_script:
  ## Install 32-bit compatibility libraries
  - sudo apt-get -qq install libc6:i386 libgcc1:i386 gcc-4.6-base:i386 libstdc++5:i386 libstdc++6:i386
  ## Use Contiki method of making sure wget succeeds.
  - WGET="travis_retry wget --continue --tries=20 --waitretry=10 --retry-connrefused --no-dns-cache --timeout 300"
  ## Install mainline ARM toolchain.
  - $WGET https://launchpad.net/gcc-arm-embedded/5.0/5-2015-q4-major/+download/gcc-arm-none-eabi-5_2-2015q4-20151219-linux.tar.bz2
  - tar xjf gcc-arm-none-eabi-5_2-2015q4-20151219-linux.tar.bz2 -C /tmp/
  - sudo cp -f -r /tmp/gcc-arm-none-eabi-5_2-2015q4/* /usr/local/
  - rm -rf /tmp/gcc-arm-none-eabi-* gcc-arm-none-eabi-*-linux.tar.bz2
  - arm-none-eabi-gcc --version

script:
  - "make"

deploy:
  provider: releases
  api_key:
    secure: "Zf+th5cK25TeJ2fTF858o304wdFXRnZf+gVwCq0gcYkI1cACtq1h1TOIit+9Ue+UUdJH5iaQBn5sjy9lNYsNQoM0FCozWy86BN2CZ96twz+cStiQOi9zJY8uXs5RK6kilI18fdvWc+yFqJ6/eMtYafysBVJhBMed/wXIwgOa6zkMiB8VvGMnW7696KDvDRXloz5rilLDTsQfEAxbxFLNE1a9kpAdOJgFxbRFkTWWc8g8ozhqqbF9rFLjNiLLWUXlhsxJErR7FJ1KrePNTuBPKSZwtIqQTri3iQAAJ4f0F/Hg+Qzok9JS9RGv+P4q1JadfYNB+MNxmdd6vQGIXfbEqy2qbtl9/3P6mJXvN+NS1lX60xVJISAR/f3V1/4RnKhSf7M0zsTWPDZDXliAPK4e/QN0KJPo2gO83f6zXYorKGl0HIMR2b6J3a6LCp22/wGpRGlCro+ogt7jbzziXnR0aaJHNfN0rEXsENmr3GTgHncDJ/5lXoTQiuoTkBbi68f4z4mdfGK2lGoOgGi/m0uEyjClHv3qLi7+51p6BGx7T4RTGd4bte8RFgBU4Toe9CGzOFF3m7LdP1cyyl3faw5PBzIGwNmWUWqkmVqVczc2w5dxd3E+He7bMNz7IHJteAb1nq71uvD9CxloePVu/hAQ8pu/xAchX0ev0cqr7H3sPck="
  file: hello.elf
  skip_cleanup: true
  on:
    tags: true
